String image    = env.JOB_NAME.split('/')[1]
String registry = "harik8/$image"
String tag      = "latest"

pipeline {
    agent {
    kubernetes {
      cloud 'kubernetes'
      label 'hadolint'
      defaultContainer 'jnlp'
      yamlFile 'hadolint/kube-pod.yaml'
  }
}
    stages {
        stage("publish") {
            steps {
                container(name: 'kaniko', shell: '/busybox/sh') {
                     withEnv(['PATH+EXTRA=/busybox:/kaniko']) {
                      sh """#!/busybox/sh
                        /kaniko/executor --context=$WORKSPACE/$image --destination $registry:$tag
                      """
                    }
                }
            }
        }
    }
}
