String[] buildElements = env.JOB_NAME.split('/')
String buildName = buildElements[buildElements.length - 2]
String registry = "quay.io/harik8"
String dockerImage = "$registry/$buildName"
String release = "latest"

pipeline {
    agent {
    kubernetes {
      cloud 'kubernetes'
      label 'hadolint'
      defaultContainer 'jnlp'
      yamlFile 'kube-pod.yaml'
  }
}
    stages {
        stage("publish") {
            steps {
                container(name: 'kaniko', shell: '/busybox/sh') {
                     withEnv(['PATH+EXTRA=/busybox:/kaniko']) {
                      sh """#!/busybox/sh
                      /kaniko/executor --context=$WORKSPACE --destination quay.io/harik8/hadolint:latest --no-push
                      """
                     }
                }
            }
        }
    }
}


